# Data Ingestion Configuration
data_ingestion:
  raw_data_dir: "/path/to/raw_data"  # Directory where raw data is stored
  file_name: "augmented_data.xlsx"  # The name of the raw data file to ingest

# Data Transformation Configuration (Optional)
data_transformation:
  transformation_method: "TF-IDF"  # Defines the method of transformation (e.g., TF-IDF, CountVectorizer)

# Model Training Configuration
model_training:
  test_size: 0.2  # Percentage of data to be used for testing (0.2 = 20%)
  random_state: 42  # Seed for random number generation to ensure reproducibility
  model_type: "RandomForest"  # The model type to be used for training (e.g., RandomForest, SVM)
  n_estimators: 100  # Number of trees for RandomForest
  max_depth: 10  # Maximum depth for RandomForest trees

# Model Evaluation Configuration
model_evaluation:
  metrics:  # List of metrics to evaluate the model on
    - accuracy
    - classification_report
  threshold: 0.5  # Threshold for binary classification (for example, in Logistic Regression)

# File Paths for saving trained models and logs
output:
  model_save_path: "/path/to/save/models"  # Directory to save trained models
  logs_path: "/path/to/logs"  # Directory for saving logs
  model_file_name: "random_forest_model.pkl"  # File name for the saved model

# Additional Configuration (Optional)
additional:
  logging_level: "INFO"  # Set logging level for the application
  enable_logging: true  # Flag to enable or disable logging
  
