data_ingestion:
  input_file_path: "data/augmented_data.xlsx"
  output_train_path: "artifacts/train_data.csv"
  output_test_path: "artifacts/test_data.csv"
  test_size: 0.2
  random_state: 42

data_validation:
  schema_file_path: "config/schema.json"
  required_columns:
    - "sentence"
    - "label"
  target_column: "label"

data_transformation:
  tfidf_max_features: 5000
  tfidf_min_df: 5
  tfidf_max_df: 0.8
  target_column: "label"

model_trainer:
  model_type: "RandomForestClassifier"
  n_estimators: 100
  random_state: 42
  model_save_path: "artifacts/tense_classifier_model.pkl"

model_evaluation:
  metric_name: "accuracy"
  metric_threshold: 0.85
  evaluation_report_path: "artifacts/evaluation_report.txt"
  
